---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FarukKadir/Microservices-With-Spring-Student-Files
          searchPaths: ConfigData
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:/offline-repository/
          
server:
  port: 8001

spring.cloud.bus.enabled: true
management.endpoints.web.exposure.include: bus-refresh  
# For simplicity, disable security when posting to bus/refresh:  
management:
  security:
    enabled: false


   